# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# SETUP CONFIGURATION.                                                        #
[build-system]
requires = ["setuptools>=64.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "getiprompt"
version = "0.1.0"
authors = [
  { name="Daan Krol", email="daan.krol@intel.com" },
  { name="Klaas Dijkstra", email="klaas.dijkstra@intel.com" },
]
description = "Geti Prompt - A modular framework for visual prompting"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.12, <3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# REQUIREMENTS                                                                #
dependencies = [
    "matplotlib==3.10.3",
    "numpy~=2.2.6",
    "opencv-python==4.11.0.86",
    "rich==14.0.0",
    "requests==2.32.4",
    "pycocotools==2.0.9",
    "scipy==1.15.3",
    "pot==0.9.5",
    "umap==0.1.1",
    "polars>=1.31.0,<2.0.0",
    "scikit-learn==1.6.1",
    "scikit-image==0.24.0",
    "openvino-model-api==0.3.0.2",
    "torch==2.7.0+cu126",
    "torchvision==0.22.0+cu126",
    "transformers==4.56.2",
    "segment-anything-hq==0.3",
    "markupsafe==3.0.2",
    "jsonargparse",
    "sam-2",
    "ftfy",
    "pytest-assume>=2.4.3",
]

[tool.uv.sources]
markupsafe = { index = "pypi" }
torch = { index = "pytorch" }
xformers = { index = "pytorch" }
torchvision = { index = "pytorch" }
torchmetrics = { index = "pytorch" }
sam-2 = { git = "https://github.com/facebookresearch/sam2.git", rev = "2b90b9f"}

[project.scripts]
getiprompt = "getiprompt.cli:main"

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu126"

[tool.hatch.build.targets.wheel]
packages = ["src/getiprompt"]

[project.optional-dependencies]
extras = [
    "xformers==0.0.30",
]
notebook = [
    "jupyter==1.1.1",
    "ipykernel==6.30.1",
]
dev = [
    "ruff==0.11.12",
    "pre-commit==4.2.0",
    "pytest==8.4.0",
    "pytest-assume",
    "build>=1.2.2.post1",
    "twine>=6.1.0",
]
dev_ui = [
    "flask==3.1.1",
]

full = [
    "getiprompt[dev, extras, notebook, dev_ui]",
]

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# RUFF CONFIGURATION                                                          #
[tool.ruff]
# Enable preview features
preview = true

# Enable rules
lint.select = ["ALL"]

lint.ignore = [
    "DOC201", # `return` is not documented in docstring
    "PLR2004", # Magic value used in comparison
    "PLR0913", # Too many arguments in function definition
    "PLR0914", # Too many local variables
    "PLR0917", # Too many positional arguments
    "FBT001",  # Boolean-typed positional argument in function definition
    "FBT002",  # Boolean default positional argument in function definition
    "PLR0912", # Too many branches
    "S101",  # Use of assert detected.
    "PT018",  # Assertion should be broken down into multiple parts
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
lint.fixable = ["ALL"]
lint.unfixable = []

# Allow unused variables when underscore-prefixed.
lint.dummy-variable-rgx = "^(_+|(_+[a-zA-Z0--9_]*[a-zA-Z0-9]+?))$"

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "per_segment_anything",
    "src/getiprompt/models/grounding_dino.py",
]

# Same as Black.
line-length = 120

# Assume Python 3.10.
target-version = "py310"

# Allow imports relative to the "src" directory.
src = ["src"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.flake8-copyright]
notice-rgx = '# Copyright \(C\) (\d{4}(-\d{4})?) Intel Corporation\r?\n# SPDX-License-Identifier: Apache-2\.0'

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["PLR6301"]  # Ignore no-self-use for test methods


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# MYPY CONFIGURATION.                                                         #
[tool.mypy]
ignore_missing_imports = true
show_error_codes = true

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# PYTEST CONFIGURATION                                                        #
[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests (deselect with '-m \"not integration\"')",
]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# NBQA CONFIGURATION                                                          #
[tool.nbqa.addopts]
ruff = ["--ignore=E402"]
