# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# SETUP CONFIGURATION.                                                        #
[build-system]
requires = ["setuptools>=64.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "getiprompt"
version = "0.1.0"
authors = [{ name = "Geti Prompt Contributors" }]
description = "Geti Prompt - A modular framework for visual prompting"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.12, <3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# REQUIREMENTS                                                                #
dependencies = [
    "matplotlib==3.10.3",
    "numpy~=2.2.6",
    "opencv-python==4.11.0.86",
    "rich==14.0.0",
    "requests==2.32.4",
    "pycocotools==2.0.9",
    "scipy==1.15.3",
    "pot==0.9.5",
    "polars>=1.31.0,<2.0.0",
    "scikit-learn==1.6.1",
    "scikit-image==0.24.0",
    "transformers==4.56.2",
    "segment-anything-hq==0.3",
    "timm==1.0.22",
    "lvis==0.5.3",
    "markupsafe==3.0.2",
    "jsonargparse",
    "sam-2",
    "ftfy",
    "torchmetrics==1.8.2",
    "openvino==2025.3.0",
    "onnx>=1.19.1",
    "onnxruntime>=1.23.2",
]

[dependency-groups]
dev = [
    "pytest~=8.3",
    "pytest-assume>=2.4.3",
    "ruff~=0.11",
    "pre-commit~=4.1",
    "mypy~=1.15",
    "pytest-cov==2.11.1",
    "pytest-html~=4.0.0",
]

[project.optional-dependencies]
# PyTorch dependency groups
cpu = [
    "torch==2.8.0",
    "torchvision==0.23.0",
]
gpu = [
    "torch==2.8.0",
    "torchvision==0.23.0",
]
xpu = [
    "torch==2.10.0.dev20251202+xpu",
    "torchvision==0.25.0.dev20251203+xpu",
    "pytorch-triton-xpu==3.5.0+gitaa01f5c2",
]
notebook = [
    "jupyter==1.1.1",
    "ipykernel==6.30.1",
]
dev = [
    "ruff==0.11.12",
    "pre-commit==4.2.0",
    "pytest==8.4.0",
    "pytest-assume",
    "build>=1.2.2.post1",
    "twine>=6.1.0",
]

full = [
    "getiprompt[dev, extras, notebook]",
]

[project.scripts]
getiprompt = "getiprompt.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/getiprompt"]

[tool.uv]
package = true
managed = true
conflicts = [
    [
        { extra = "cpu" },
        { extra = "gpu" },
        { extra = "xpu" },
    ],
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[[tool.uv.index]]
name = "pytorch-xpu"
url = "https://download.pytorch.org/whl/nightly/xpu"
explicit = true

[tool.uv.sources]
sam-2 = { git = "https://github.com/facebookresearch/sam2.git", rev = "2b90b9f"}
torch = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-cu126", extra = "gpu" },
    { index = "pytorch-xpu", extra = "xpu" },
]
torchvision = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-cu126", extra = "gpu" },
    { index = "pytorch-xpu", extra = "xpu" },
]
pytorch-triton-xpu = [
    { index = "pytorch-xpu", extra = "xpu" },
]

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# RUFF CONFIGURATION                                                          #
[tool.ruff]
# Enable preview features
preview = true

# Enable rules
lint.select = ["ALL"]

lint.ignore = [
    "DOC201", # `return` is not documented in docstring
    "PLR2004", # Magic value used in comparison
    "PLR0913", # Too many arguments in function definition
    "PLR0914", # Too many local variables
    "PLR0917", # Too many positional arguments
    "FBT001",  # Boolean-typed positional argument in function definition
    "FBT002",  # Boolean default positional argument in function definition
    "PLR0912", # Too many branches
    "S101",  # Use of assert detected.
    "PT018",  # Assertion should be broken down into multiple parts
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
lint.fixable = ["ALL"]
lint.unfixable = []

# Allow unused variables when underscore-prefixed.
lint.dummy-variable-rgx = "^(_+|(_+[a-zA-Z0--9_]*[a-zA-Z0-9]+?))$"

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "src/getiprompt/models/grounding_dino.py",
]

# Same as Black.
line-length = 120

# Minimum supported Python version.
target-version = "py310"

# Allow imports relative to the "src" directory.
src = ["src"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.flake8-copyright]
notice-rgx = '# Copyright \(C\) (\d{4}(-\d{4})?) Intel Corporation\r?\n# SPDX-License-Identifier: Apache-2\.0'

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["PLR6301"]  # Ignore no-self-use for test methods


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# MYPY CONFIGURATION.                                                         #
[tool.mypy]
ignore_missing_imports = true
show_error_codes = true

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# PYTEST CONFIGURATION                                                        #
[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests (deselect with '-m \"not integration\"')",
]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# NBQA CONFIGURATION                                                          #
[tool.nbqa.addopts]
ruff = ["--ignore=E402"]
